// import bot from "./icons/bot.png";
// import user from "./icons/user.png";
// import styles from "./Chat.css";

// //sourced from https://www.sitepoint.com/build-chatgpt-clone-react-openai-api/

// export default function Message({ role, content }) {
//   return (
//     <div className={styles.wrapper}>
//       <div>
//         <img
//           src={role === "assistant" ? bot : user}
//           className={styles.avatar}
//           alt="profile avatar"
//         />
//       </div>
//       <div>
//         <p>{content}</p>
//       </div>
//     </div>
//   );
// }

// //Generated by ChatGPT
// // import { useState } from "react";

// // function Chat() {
// //   const [messages, setMessages] = useState([]);
// //   const [input, setInput] = useState("");

// //   const handleSend = () => {
// //     setMessages([...messages, { text: input, sender: "user" }]);
// //     setInput("");

// //     // Simulate AI response
// //     setTimeout(() => {
// //       setMessages((messages) => [
// //         ...messages,
// //         { text: "AI response", sender: "ai" },
// //       ]);
// //     }, 1000);
// //   };

// //   return (
// //     <div>
// //       <div>
// //         {messages.map((message, index) => (
// //           <div key={index}>{message.text}</div>
// //         ))}
// //       </div>
// //       <input
// //         type="text"
// //         value={input}
// //         onChange={(e) => setInput(e.target.value)}
// //         onKeyDown={(e) => e.key === "Enter" && handleSend()}
// //       />
// //       <button onClick={handleSend}>Send</button>
// //     </div>
// //   );
// // }

// // export default Chat;

// //Original code, before we added the AI response

// // // Importing the 'useState' hook from the 'react' library
// // import { useState } from "react";
// // // Importing the 'css' function from the '@emotion/react' library
// // import { css } from "@emotion/react";

// // // Defining the CSS styles for the chat container
// // const chatContainerStyle = css`
// //   display: flex;
// //   flex-direction: column;
// //   height: 400px;
// //   border: 1px solid #ccc;
// //   padding: 10px;
// //   overflow: auto;
// // `;

// // // Defining the CSS styles for the input field
// // const inputStyle = css`
// //   margin-top: 10px;
// // `;

// // // Defining the Chat component
// // function Chat() {
// //   // Declaring state variables using the 'useState' hook
// //   const [messages, setMessages] = useState([]);
// //   const [input, setInput] = useState("");

// //   // Function to handle sending a message
// //   const handleSend = () => {
// //     // Updating the 'messages' state by adding the new input message
// //     setMessages([...messages, input]);
// //     // Clearing the input field
// //     setInput("");
// //   };

// //   // Rendering the Chat component
// //   return (
// //     <div>
// //       {/* Rendering the chat container */}
// //       <div css={chatContainerStyle}>
// //         {/* Mapping through the 'messages' array and rendering each message */}
// //         {messages.map((message, index) => (
// //           <div key={index}>{message}</div>
// //         ))}
// //       </div>
// //       {/* Rendering the input field */}
// //       <input
// //         css={inputStyle}
// //         type="text"
// //         value={input}
// //         onChange={(e) => setInput(e.target.value)}
// //         onKeyDown={(e) => e.key === "Enter" && handleSend()}
// //       />
// //       {/* Rendering the send button */}
// //       <button onClick={handleSend}>Send</button>
// //     </div>
// //   );
// // }

// // // Exporting the Chat component as the default export
// // export default Chat;
